version: '3'

networks:
  kws0_net:
    driver: bridge

services:
  nginx:
    networks:
      - kws0_net
    build: ./nginx
    restart: always
    image: nginx_cust
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  mariadb:
    image: mariadb:10.6.0
    ports:
      - "6006:3306"
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ------
        MYSQL_DATABASE: kws
        MYSQL_USER: root
        MYSQL_PASSWORD: ------ 
    networks:
      - kws0_net
  phpmyadmin:
    image: phpmyadmin:5.1.0
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: -------
      PMA_ABSOLUTE_URI: https://kws0.kangnam.ac.kr/myadmin/
    networks:
      - kws0_net      
    links:
      - "mariadb:db"
